### ISSUE TITLE
ValueError: Unknown VDF_VERSION: 0x07564427

### ISSUE THREAD

**Issue by Kira-PH** [gasinvein/steam-desktop-updater#2]
Is there any other information I can provide?

Traceback (most recent call last):
  File "./steam_desktop_updater.py", line 134, in <module>
    create_desktop_data(steam_root=args.steam_root, destdir=args.datatir, steam_cmd=args.steam_command)
  File "./steam_desktop_updater.py", line 86, in create_desktop_data
    appinfo_data = appinfo.load(af)
  File "/home/lelani/.local/lib/python3.6/site-packages/steamfiles/appinfo.py", line 29, in load
    return loads(fp.read(), wrapper=wrapper)
  File "/home/lelani/.local/lib/python3.6/site-packages/steamfiles/appinfo.py", line 42, in loads
    return AppinfoDecoder(data, wrapper=wrapper).decode()
  File "/home/lelani/.local/lib/python3.6/site-packages/steamfiles/appinfo.py", line 102, in decode
    raise ValueError('Unknown VDF_VERSION: 0x{0:08x}'.format(header['version']))
ValueError: Unknown VDF_VERSION: 0x07564427

**Comment by gasinvein** [comment]
I guess it's a steamfiles issue leovp/steamfiles#5, fixed in master.

**Comment by Kira-PH** [comment]
Thanks, did you push? :)

**Comment by gasinvein** [comment]
I meant steamfiles's master branch. It's latest release (0.1.3 or so) doesn't support VDF version 0x07564427.
You can install steamfiles from git master like so:
`pip3 install --upgrade --user git+https://github.com/leovp/steamfiles.git`

**Comment by Kira-PH** [comment]
OH! Ok! Thanks again.
